//! Org-scoped UI + agent-response language.
//!
//! One row per supported language. The single source of truth is the
//! `as_str` label generated by [`crate::str_enum!`] — it backs the
//! `organizations.default_language` column CHECK, the JSON wire format,
//! and the lookup key in the prompt registry. Adding a new language is a
//! one-line edit here plus a matching TOML file in `src/prompts/`.

use crate::str_enum;

str_enum! {
    /// Supported languages for the agent's response and the web chrome.
    ///
    /// Order is wire-stable (driven by `as_str`); the variant order here
    /// only matters for `ALL`. Bumping the set means a paired schema
    /// migration (extend the `organizations.default_language` CHECK) and
    /// a new prompt TOML file.
    pub enum Language {
        En => "en",
        Vi => "vi",
    }
}

impl Language {
    /// Process-wide fallback. The default-language seed at first sign-up
    /// goes through [`Self::from_locale_hint`]; this constant is only the
    /// last-resort value when nothing matches.
    pub const DEFAULT: Self = Self::En;

    /// Derive a [`Language`] from the locale hints we receive at OAuth
    /// callback time.
    ///
    /// Rules:
    /// 1. Google's `locale` (from `userinfo`) wins if its primary subtag
    ///    matches a known language.
    /// 2. Otherwise the inbound `Accept-Language` primary subtag is
    ///    tried. (Captured at `/auth/google/login` and stashed on the
    ///    `oauth_login_states` row.)
    /// 3. Otherwise [`Self::DEFAULT`].
    ///
    /// The primary subtag is the prefix before `-` or `_`, lowercased.
    /// We do not honour quality-value (`;q=`) ordering — the FE-supplied
    /// header in the login round-trip carries the user's top preference
    /// at the front, and Google's locale is never a list. Splitting on
    /// `,` covers the multi-value `Accept-Language` shape.
    #[must_use]
    pub fn from_locale_hint(google: Option<&str>, accept_language: Option<&str>) -> Self {
        if let Some(lang) = google.and_then(parse_primary_tag) {
            return lang;
        }
        if let Some(lang) = accept_language.and_then(|raw| {
            raw.split(',')
                .map(str::trim)
                .filter_map(|entry| entry.split(';').next())
                .find_map(parse_primary_tag)
        }) {
            return lang;
        }
        Self::DEFAULT
    }
}

/// Lowercase the primary subtag (everything before `-`, `_`, or `;`) and
/// look it up in [`Language::ALL`]. Returns `None` for the empty string
/// and for tags we don't support.
fn parse_primary_tag(raw: &str) -> Option<Language> {
    let primary = raw.split(['-', '_', ';']).next()?.trim();
    if primary.is_empty() {
        return None;
    }
    let lower = primary.to_ascii_lowercase();
    Language::parse(lower.as_str())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn from_google_simple() {
        assert_eq!(Language::from_locale_hint(Some("vi"), None), Language::Vi);
        assert_eq!(Language::from_locale_hint(Some("en"), None), Language::En);
    }

    #[test]
    fn from_google_with_region() {
        assert_eq!(
            Language::from_locale_hint(Some("vi-VN"), None),
            Language::Vi
        );
        assert_eq!(
            Language::from_locale_hint(Some("en-US"), None),
            Language::En
        );
    }

    #[test]
    fn from_google_case_insensitive() {
        assert_eq!(Language::from_locale_hint(Some("VI"), None), Language::Vi);
        assert_eq!(
            Language::from_locale_hint(Some("EN_GB"), None),
            Language::En
        );
    }

    #[test]
    fn falls_back_to_accept_language_when_google_unknown() {
        // Google returned a language we don't speak — Accept-Language wins.
        assert_eq!(
            Language::from_locale_hint(Some("fr"), Some("vi-VN,en;q=0.8")),
            Language::Vi
        );
    }

    #[test]
    fn google_wins_when_both_match() {
        assert_eq!(
            Language::from_locale_hint(Some("vi"), Some("en")),
            Language::Vi
        );
        assert_eq!(
            Language::from_locale_hint(Some("en"), Some("vi")),
            Language::En
        );
    }

    #[test]
    fn from_accept_language_only() {
        assert_eq!(
            Language::from_locale_hint(None, Some("vi-VN,en;q=0.8")),
            Language::Vi
        );
        assert_eq!(Language::from_locale_hint(None, Some("en")), Language::En);
        assert_eq!(
            Language::from_locale_hint(None, Some("en-GB,en;q=0.9")),
            Language::En
        );
    }

    #[test]
    fn falls_back_to_default_when_nothing_matches() {
        assert_eq!(Language::from_locale_hint(None, None), Language::DEFAULT);
        assert_eq!(
            Language::from_locale_hint(Some("fr"), Some("de-DE")),
            Language::DEFAULT
        );
        assert_eq!(
            Language::from_locale_hint(Some(""), Some("")),
            Language::DEFAULT
        );
    }

    #[test]
    fn accept_language_skips_unsupported_then_picks_supported() {
        // Real browser pattern: top preference is unsupported, second is supported.
        assert_eq!(
            Language::from_locale_hint(None, Some("fr-FR;q=1.0, vi;q=0.8, en;q=0.5")),
            Language::Vi
        );
    }

    #[test]
    fn parse_round_trip() {
        for &lang in Language::ALL {
            assert_eq!(Language::parse(lang.as_str()), Some(lang));
        }
        assert_eq!(Language::parse("fr"), None);
        assert_eq!(Language::parse(""), None);
        assert_eq!(Language::parse("EN"), None); // case-sensitive at this layer
    }
}
